# Generated by Django 2.2.4 on 2021-06-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radana_app', '0003_auto_20210603_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
