# Generated by Django 2.2.4 on 2021-06-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radana_app', '0007_auto_20210604_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
