# Generated by Django 2.2.4 on 2021-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radana_app', '0010_auto_20210604_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
