# Generated by Django 2.2.4 on 2021-06-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radana_app', '0011_auto_20210605_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
